In [1]:
import pandas as pd
data = pd.read_csv("C:/Users/hasan/Documents/DS/Udemy/DL/ANN/annclassification_krish/Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [2]:
df = data.drop(['RowNumber', "CustomerId", "Surname"], axis=1)
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [3]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
num_feature = [feature for feature in df.columns if df[feature].dtype!="O" and feature not in ["EstimatedSalary", "Exited"]]
cat_feature = [feature for feature in df.columns if df[feature].dtype=="O"]
cat_feature.append("Exited")

In [5]:
num_feature

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember']

In [6]:
cat_feature

['Geography', 'Gender', 'Exited']

In [7]:
for feature in cat_feature:
    print(feature)
    print(len(feature)*"-")
    print(df[feature].unique())
    print("")

Geography
---------
['France' 'Spain' 'Germany']

Gender
------
['Female' 'Male']

Exited
------
[1 0]



In [8]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [9]:
X = df.drop("EstimatedSalary", axis=1)
y = df["EstimatedSalary"]

In [10]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...    
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [12]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
oh_encoder = OneHotEncoder(drop="first")
scaler = StandardScaler()

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [14]:
num_pipline = Pipeline(
    steps=[
        ("StandardScaler", scaler)
    ]
)

cat_pipline = Pipeline(
    steps=[
        ("OneHotEncoder", oh_encoder)
    ]
)

preprocessor = ColumnTransformer(
    [
        ("num_pipeline", num_pipline, num_feature),
        ("cat_pipline", cat_pipline, cat_feature)
    ]
)

In [15]:
# transformation of train data 
X_train = preprocessor.fit_transform(X_train)

# transformation of train data 
X_test = preprocessor.transform(X_test)

In [16]:
X.shape, X_train.shape, X_test.shape

((10000, 10), (7500, 11), (2500, 11))

In [17]:
X.size, X_train.size, X_test.size

(100000, 82500, 27500)

In [18]:
X_train

array([[-0.66809142, -0.56092417, -0.00386458, ...,  0.        ,
         1.        ,  0.        ],
       [-1.36419169,  0.58291123, -1.38407173, ...,  0.        ,
         0.        ,  1.        ],
       [-1.64470972,  0.86887008,  0.686239  , ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.39796295, -0.84688303,  1.37634257, ...,  1.        ,
         1.        ,  0.        ],
       [ 1.36826163,  0.20163276, -0.00386458, ...,  0.        ,
         0.        ,  0.        ],
       [-0.60575408, -0.75156341,  1.37634257, ...,  0.        ,
         1.        ,  0.        ]])

In [19]:
import pickle

In [20]:
# saving preprocessor object 
with open("artifact/preprocessor.pkl", "wb") as file_obj:
    pickle.dump(preprocessor, file_obj)

In [21]:
import numpy as np

In [22]:
train_data = np.c_[X_train, y_train]
test_data = np.c_[X_test, y_test]

In [23]:
train_data[:, -1], test_data[:, -1]

(array([ 34215.58,  41042.4 ,  48545.1 , ..., 175795.87, 176945.96,
         20492.16]),
 array([ 60651.77,  65039.9 , 175070.94, ...,  72846.58, 169653.32,
        127623.36]))

In [24]:
pd.DataFrame(train_data).to_csv("artifact/train.csv")
pd.DataFrame(test_data).to_csv("artifact/test.csv")